# Site settings
author: astronomical-reducer-9741
title: 
header-img: img/home-bg.png
email: vinh.v.tran@ucdenver.edu
copyright_name: astronomical-reducer-9741
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  travinh

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
